apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  DB_URI: mongodb+srv://utkarshsharma9571_db_user:Ah7ErKMCsUCVRrZ7@cluster0.ivqp2h.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  JWT_SECRET: Utkarsh9571
