version: "3.8"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.development.local
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend

volumes:
  mongo-data:
